### ISSUE TITLE
Unable to invoke no-args constructor for class com.pipl.api.search.SearchAPIResponse.

### ISSUE THREAD

**Issue by yathit** [piplcom/piplapis-java#2]
I tried your library in my appengine, but fail to execute the request due to the following error:

>    Unable to invoke no-args constructor for class com.pipl.api.search.SearchAPIResponse. Register an InstanceCreator with Gson for this type may fix this problem.

```
java.lang.RuntimeException: Unable to invoke no-args constructor for class com.pipl.api.search.SearchAPIResponse. Register an InstanceCreator with Gson for this type may fix this problem.
at com.google.gson.internal.ConstructorConstructor$12.construct(ConstructorConstructor.java:210)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:162)
at com.google.gson.Gson.fromJson(Gson.java:803)
at com.google.gson.Gson.fromJson(Gson.java:768)
at com.google.gson.Gson.fromJson(Gson.java:717)
at com.google.gson.Gson.fromJson(Gson.java:689)
at com.pipl.api.data.Utils.fromJson(Utils.java:160)
at com.pipl.api.search.SearchAPIRequest.send(SearchAPIRequest.java:548)
at com.pipl.api.search.SearchAPIRequest.send(SearchAPIRequest.java:572)
at ydn.social.pipl.Pipl.getByEmail(Pipl.java:27)
at ydn.iam.SocialServlet.doPost(SocialServlet.java:58)
at ydn.iam.SocialServlet.doGet(SocialServlet.java:24)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
at com.googlecode.objectify.cache.AsyncCacheFilter.doFilter(AsyncCacheFilter.java:58)
at com.googlecode.objectify.ObjectifyFilter.doFilter(ObjectifyFilter.java:48)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at com.google.appengine.api.socket.dev.DevSocketFilter.doFilter(DevSocketFilter.java:74)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at com.google.appengine.tools.development.ResponseRewriterFilter.doFilter(ResponseRewriterFilter.java:127)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at com.google.appengine.tools.development.HeaderVerificationFilter.doFilter(HeaderVerificationFilter.java:34)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at com.google.appengine.api.blobstore.dev.ServeBlobFilter.doFilter(ServeBlobFilter.java:63)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at com.google.appengine.tools.development.StaticFileFilter.doFilter(StaticFileFilter.java:125)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectRequest(DevAppServerModulesFilter.java:366)
at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectModuleRequest(DevAppServerModulesFilter.java:349)
at com.google.appengine.tools.development.DevAppServerModulesFilter.doFilter(DevAppServerModulesFilter.java:116)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
at com.google.appengine.tools.development.DevAppEngineWebAppContext.handle(DevAppEngineWebAppContext.java:98)
at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
at com.google.appengine.tools.development.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:491)
at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
at org.mortbay.jetty.Server.handle(Server.java:326)
at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
```

Caused by: java.lang.UnsupportedOperationException: Cannot allocate class com.pipl.api.search.SearchAPIResponse
    at com.google.gson.internal.UnsafeAllocator$4.newInstance(UnsafeAllocator.java:100)
    at com.google.gson.internal.ConstructorConstructor$12.construct(ConstructorConstructor.java:207)
    ... 51 more

Caused by:

```
java.lang.UnsupportedOperationException: Cannot allocate class com.pipl.api.search.SearchAPIResponse
at com.google.gson.internal.UnsafeAllocator$4.newInstance(UnsafeAllocator.java:100)
at com.google.gson.internal.ConstructorConstructor$12.construct(ConstructorConstructor.java:207)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:162)
at com.google.gson.Gson.fromJson(Gson.java:803)
at com.google.gson.Gson.fromJson(Gson.java:768)
at com.google.gson.Gson.fromJson(Gson.java:717)
at com.google.gson.Gson.fromJson(Gson.java:689)
at com.pipl.api.data.Utils.fromJson(Utils.java:160)
at com.pipl.api.search.SearchAPIRequest.send(SearchAPIRequest.java:548)
at com.pipl.api.search.SearchAPIRequest.send(SearchAPIRequest.java:572)
at ydn.social.pipl.Pipl.getByEmail(Pipl.java:27)
at ydn.iam.SocialServlet.doPost(SocialServlet.java:58)
at ydn.iam.SocialServlet.doGet(SocialServlet.java:24)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
at com.googlecode.objectify.cache.AsyncCacheFilter.doFilter(AsyncCacheFilter.java:58)
at com.googlecode.objectify.ObjectifyFilter.doFilter(ObjectifyFilter.java:48)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at com.google.appengine.api.socket.dev.DevSocketFilter.doFilter(DevSocketFilter.java:74)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at com.google.appengine.tools.development.ResponseRewriterFilter.doFilter(ResponseRewriterFilter.java:127)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at com.google.appengine.tools.development.HeaderVerificationFilter.doFilter(HeaderVerificationFilter.java:34)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at com.google.appengine.api.blobstore.dev.ServeBlobFilter.doFilter(ServeBlobFilter.java:63)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at com.google.appengine.tools.development.StaticFileFilter.doFilter(StaticFileFilter.java:125)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectRequest(DevAppServerModulesFilter.java:366)
at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectModuleRequest(DevAppServerModulesFilter.java:349)
at com.google.appengine.tools.development.DevAppServerModulesFilter.doFilter(DevAppServerModulesFilter.java:116)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
at com.google.appengine.tools.development.DevAppEngineWebAppContext.handle(DevAppEngineWebAppContext.java:98)
at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
at com.google.appengine.tools.development.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:491)
at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
at org.mortbay.jetty.Server.handle(Server.java:326)
at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
```

**Comment by yathit** [comment]
After adding non-arg construction to data classes, it runs. But, got empty result. Due to restriction on my appengine platform, I use REST API directly via [GAE URLFetch API](https://cloud.google.com/appengine/docs/java/urlfetch/)

```
private static final Logger logger = Logger.getLogger(Pipl.class.getName());

static private Person fetchByEmail(String email) {

    if (email == null || email.isEmpty() || !email.contains("@")
            || !email.contains(".")) {
        return null;
    }
    String json = "";
    try {
        URL url = new URL("https://api.pipl.com/search/v3/json/?key=" +
                API_KEY + "&email=" + email);
        HttpURLConnection connection = (HttpURLConnection) url.openConnection();
        if (connection.getResponseCode() == HttpURLConnection.HTTP_OK) {
            BufferedReader reader = new BufferedReader(new InputStreamReader(url.openStream()));
            StringBuilder res = new StringBuilder();
            String line;
            while ((line = reader.readLine()) != null) {
                res.append(line);
            }
            reader.close();
            Gson gson = new GsonBuilder().setDateFormat("yyyy-MM-dd").create();
            json = res.toString();
            logger.info(json);
            SearchAPIResponse resp = gson.fromJson(json, SearchAPIResponse.class);
            Person person = resp.getPerson();
            person.id = "email " + email;
            person.modified = new Date();
            return person;
        } else {
            logger.warning(url.toString() + " " + connection.getResponseCode());
        }
    } catch (MalformedURLException e) {
        e.printStackTrace();
    } catch (IOException e) {
        e.printStackTrace();
    }
    return null;
}
```

Here is relevent debug log

```
Dec 22, 2014 12:24:03 AM ydn.social.pipl.Pipl fetchByEmail
```

INFO: {"@http_status_code": 200, "@records_count": 5, "@available_records": 7, "warnings": [], "query": {"emails": [{"address": "kyawtun@yathit.com", "address_md5": "6c0f846c53067579dbc302f12fa2b909"}]}, "person": {}, "records": [{"@query_params_match": false, "source": {"@is_sponsored": false, "url": "http://www.linkedin.com/pub/kyaw-sett-tun/b/380/509", "domain": "linkedin.com", "name": "Professional Profile & Networking - LinkedIn", "category": "professional_and_business"}, "names": [{"first": "Kyaw", "middle": "Sett", "last": "Tun", "display": "Kyaw Sett Tun"}], "user_ids": [{"content": "33758937"}, {"content": "B/380/509"}]}, {"@query_params_match": false, "source": {"@is_sponsored": false, "url": "http://www.facebook.com/people/_/1039712017", "domain": "facebook.com", "name": "Personal Web Profile - Facebook", "category": "personal_profiles"}, "names": [{"first": "Kyaw", "middle": "Sett", "last": "Tun", "display": "Kyaw Sett Tun"}], "images": [{"url": "http://graph.facebook.com/1039712017/picture?type=large"}], "usernames": [{"content": "kyaw.s.tun.7"}], "user_ids": [{"content": "1039712017"}], "related_urls": [{"content": "http://www.facebook.com/kyaw.s.tun.7"}]}, {"@query_params_match": false, "source": {"@is_sponsored": false, "url": "https://plus.google.com/111355618070688049129/about", "domain": "plus.google.com", "name": "Personal Profile - Google Profiles", "category": "personal_profiles"}, "names": [{"first": "Kyaw", "last": "Tun", "display": "Kyaw Tun"}], "images": [{"url": "https://lh4.googleusercontent.com/-CfatLvOxPDM/AAAAAAAAAAI/AAAAAAAAAAA/djOJA_fdUA0/photo.jpg"}], "user_ids": [{"content": "111355618070688049129"}]}, {"@query_params_match": false, "source": {"@is_sponsored": false, "url": "http://www.facebook.com/people/_/1206675029", "domain": "facebook.com", "name": "Personal Web Profile - Facebook", "category": "personal_profiles"}, "names": [{"first": "Kyaw", "last": "Tun", "display": "Kyaw Tun"}], "images": [{"url": "http://graph.facebook.com/1206675029/picture?type=large"}], "usernames": [{"content": "kyaw.tun.1654"}], "user_ids": [{"content": "1206675029"}], "related_urls": [{"content": "http://www.facebook.com/kyaw.tun.1654"}]}, {"@query_params_match": false, "source": {"@is_sponsored": false, "url": "http://www.facebook.com/people/_/100000461676717", "domain": "facebook.com", "name": "Personal Web Profile - Facebook", "category": "personal_profiles"}, "names": [{"first": "Bernard", "last": "D'ambrosio", "display": "Bernard D'ambrosio"}], "images": [{"url": "http://graph.facebook.com/100000461676717/picture?type=large"}], "user_ids": [{"content": "100000461676717"}]}], "suggested_searches": []}

So it looks like url fetch is OK.
